name: Download artifacts test

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Download artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: github-pages
      - name: Display structure of downloaded files
        run: ls -R
