name: Clean up after PR closed

on:
  pull_request:
    types:
      - closed

jobs:
  remove-storybook:
    name: Remove Storybook site associated with closed PR
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Setup user
        uses: fregante/setup-git-user@v2
      - name: Read deployment ID from commit
        id: parse-commit
        run: MSG=$(git --no-pager log -n 1 --pretty=format:%s ${{ github.event.pull_request.head.ref }}) && echo "deployment_id=${MSG%%/*}" >> $GITHUB_OUTPUT
      - name: Remove branch folder and commit changes
        run: |
          rm -rf ${{ github.event.pull_request.head.ref }}
          git add .
          git commit -m "removed ${{ github.event.pull_request.head.ref }}"
          git push
      - name: Complete deployment (success)
        if: steps.parse-commit.outputs.deployment_id != ''
        uses: octokit/request-action@v2.1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/${{ github.repository }}/deployments/{deployment_id}/statuses
          deployment_id: ${{ steps.parse-commit.outputs.deployment_id }}
          state: inactive
