name: Clean up after PR closed

on:
  pull_request:
    types:
      - closed

jobs:
  remove-storybook:
    name: Remove Storybook site associated with closed PR
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Setup user
        uses: fregante/setup-git-user@v2
      - name: Remove branch folder and commit changes
        run: |
          rm -rf ${{ github.event.pull_request.head.ref }}
          git add .
          git commit -m "removed ${{ github.event.pull_request.head.ref }}"
          git push
