# Publish versioned Storybook builds by deploying to subfolders in gh-pages branch.
name: Deploy by branch v3

on:
  push:
    branches:
      - "*"

jobs:
  create-deployment:
    name: Create GH deployment
    runs-on: ubuntu-22.04
    permissions:
      deployments: write
    steps:
      - name: Create deployment
        uses: octokit/request-action@v2.1.7
        id: create-deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/${{ github.repository }}/deployments
          ref: ${{ github.ref_name }}
          environment: docs-${{ github.ref_name }}
          required_contexts: "[]"
          auto_merge: false
    outputs:
      deployment_id: ${{ fromJson(steps.create-deployment.outputs.data).id }}

  publish-storybook:
    name: Build and deploy Storybook
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: echo ${{ github.sha }}
      - name: Install dependencies
        run: npm ci
        working-directory: app
      - name: Build
        id: build
        run: npm run build-storybook -- -o static
        # run: exit 1
        working-directory: app
      - name: Deploy to Pages under branch name
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: app/static
          destination_dir: ${{ github.ref_name }}
          full_commit_message: ${{ github.sha }}/${{ github.ref_name }}
      # Optional deploy to 'latest'.
      # - name: Deploy to Pages under "latest" (optional)
      #   if: inputs.latest
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: app/static
      #     destination_dir: latest
      - name: Format deployment URL
        id: url
        env:
          REPO: ${{ github.repository }}
        run: echo "url=https://${{ github.repository_owner }}.github.io/${REPO##*/}/${{ github.ref_name }}" >> $GITHUB_OUTPUT
    outputs:
      url: ${{ steps.url.outputs.url }}

  complete-deployment:
    name: Update GH deployment status
    runs-on: ubuntu-22.04
    if: always()
    needs:
      - create-deployment
      - publish-storybook
    permissions:
      deployments: write
    steps:
      - name: Complete deployment (success)
        if: needs.publish-storybook.result == 'success'
        uses: octokit/request-action@v2.1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/${{ github.repository }}/deployments/{deployment_id}/statuses
          deployment_id: ${{ needs.create-deployment.outputs.deployment_id }}
          ref: ${{ github.ref_name }}
          environment: docs-${{ github.ref_name }}
          state: success
          environment_url: ${{ needs.publish-storybook.outputs.url }}
      - name: Complete deployment (failure)
        if: needs.publish-storybook.result == 'failure'
        uses: octokit/request-action@v2.1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/${{ github.repository }}/deployments/{deployment_id}/statuses
          deployment_id: ${{ needs.create-deployment.outputs.deployment_id }}
          ref: ${{ github.ref_name }}
          environment: docs-${{ github.ref_name }}
          state: failure
