# Deploy to github-pages branch instead of artifact upload.

name: Deploy by branch v2

on: push

jobs:
  build:
    name: Deploy Storybook to branch subfolder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: npm ci
        working-directory: app
      - run: npm run build-storybook -- -o static
        working-directory: app
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: ${GITHUB_REF##*/}
